decider:
  ros__parameters:
    _: null #placeholder/dummy
    # topics:
    #   sub:
    #     camera:
    #     lidar:  
    #   pub:
    params:
      timer_delay: 200
    #  time_diff_thr:
    #  disgard_time_thr: