wayfinding:
  ros__parameters:
    _: null #dummy
    # topics:
      # flux:
        # camera_info:  "/zed2i_c1/zed_node_c1/rgb/camera_info"
        # imu:          "/imu/data"
        # pointcloud:   "/zed2i_c1/zed_node_c1/point_cloud/cloud_registered"
        # rgb_image:    "/zed2i_c1/zed_node_c1/rgb/image_rect_color"
      # dmc:
      # pub: "/path_width"
    # params:
      # angle_filter: 75.0
      # params.optimal_line_angle: 90.0
    # debug:
      # metric_output_file: "metric_table"