visualize_path:
  ros__parameters:
    _: null #placeholder/dummy
    # robot_specific:
    #   wheel_inside:                 # Width of the Wheels   
    #   wheel_width:                  # Distance of the vertical Plane in the center of the Robot to the vertical inside Plane of the Wheels   